# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f14bc0d7fba3502958fe4c0461d4bb83bf4e2184e10924af3571e9d654451135e44a6704be7f35fa27c6af7f102660e2c5324accdd37961c652c6eeee4afafa4

test:
  secret_key_base: 13da994caaae7460c0aa1bb7f41fe33fe8d3595a88cee0e77ad99171973d6c77f4afdd2d78d0af3ae7b9e7b719131510d92c7075474a2d4a10c66f0bbeff0e7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
